# Generated by Django 3.1.1 on 2020-09-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gg_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gs_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='hg_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='hs_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_access',
        ),
        migrations.AddField(
            model_name='game',
            name='g_pattern',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='h_pattern',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.IntegerField(default=1, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='general_level',
            field=models.IntegerField(blank=True, default=1, verbose_name='General Level'),
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.IntegerField(verbose_name='Level'),
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
