# Generated by Django 3.1.1 on 2020-09-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20200916_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frnd', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
