# Generated by Django 3.1.1 on 2020-09-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200916_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
